### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by marbetschar** [groue/GRMustache#106]
Adding Carthage support would be very cool!

Right now when I check out the project using Carthage, I receive the following error message:
```
*** Skipped building GRMustache due to the error:
Dependency "GRMustache" has no shared framework schemes for any of the platforms: iOS
```

**Comment by marbetschar** [comment]
Seems like the  `master` branch works since there is a shared `GRMustache` framework scheme in it:

```
github "groue/GRMustache" "master"
```

But I'm quite unsure if the `master` branch is safe for production use?? Any better options?

**Comment by groue** [comment]
Hello @marbetschar 

I've been lazy completing the work on the framework support, I'm sorry.

**Comment by groue** [comment]
Is there a way for you to avoid the framework for now, or do you really need it?

**Comment by marbetschar** [comment]
Hi @groue!

Unfortunately I really need the framework :(

As up now I was able to build and include it into my project using Carthage, so `master` seems to work at first sight - without going into any testing yet.

So I'm wondering what you mean with "you weren't able to complete the work on the framework support"? And if it's save to use the framework in production?

**Comment by groue** [comment]
> Unfortunately I really need the framework :(

No problem, we're in 2016 now - static libs are so 2010 :-)

> As up now I was able to build and include it into my project using Carthage, so master seems to work at first sight - without going into any testing yet.
> So I'm wondering what you mean with "you weren't able to complete the work on the framework support"? And if it's save to use the framework in production?

I have been working on a framework-only branch, with improved compatibility with [GRMustache.swift](https://github.com/groue/GRMustache.swift). This work is stalled, that's what I'm referring to.

But if you were able to build GRMustache with Carthage, I do not expect that you have any problem. Just open an issue in this case!

**Comment by marbetschar** [comment]
Ok, cool! Thanks!!!

**Comment by groue** [comment]
Happy Mustache!
