### ISSUE TITLE
Existing Project - Not Working

### ISSUE THREAD

**Issue by earblast** [groue/GRMustache#90]
Have taken over an existing project that incorporates GRMustache. There are seven files that receive error messages because they are "not available." I have run install pod etc as indicated in setup section. 

The four main files present are: GRMustache .h/m, GRMustacheVersion.h and GRMustache_private.h.

In addition there are Support files such as: Pods -app name- GRMustache.xcconfig, Pods - app name - GRMustache-Private.config, Pods - app name - GRMustache-dummy.m and Pods - app name - GRMustache-prefix.pch.

SO the private files such as GRMustacheAvailabilityMacros_private.h show as "File Not Found"...suggested steps to rectify much appreciated.

**Comment by groue** [comment]
Hi @earblast. I recommend that you setup a fresh empty project on the side, add the GRMustache pod, run pod install, check that the fresh project runs, and finally compare the two projects in order to see what's wrong in the existing one.

**Comment by earblast** [comment]
Thank you. Seems to have been a corrupted podfile, if such a thing exists....Rebuilt the podfile, installed correctly, no errors

**Comment by groue** [comment]
Cool! So everything works fine now?

**Comment by earblast** [comment]
Sorry for delay. All is working  thanks!

**Comment by groue** [comment]
Happy Mustache :-)
