### ISSUE TITLE
Non-portable filenames

### ISSUE THREAD

**Issue by sid0** [groue/GRMustache#93]
There are a bunch of filenames in the test suite that aren't portable across platforms. Specifically, filenames with colons in them are not supported on Windows.

Here's a list of files that aren't portable: https://gist.github.com/sid0/adbe8bbad152b6510102

It'd be great if you could rename them to something portable. Using an underscore maybe? Or maybe just turn them into subdirectories (`groue/GRMustache`) etc.

**Comment by groue** [comment]
Hi @sid0! I just pushed your suggested renaming. Is it OK for you now? Do you need a formal (tagged) release?

**Comment by sid0** [comment]
Thanks. We don't need a formal release for this.

**Comment by groue** [comment]
Happy Mustache, then!
